/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FijiITKInterface_OOFTubularityMeasure */

#ifndef _Included_FijiITKInterface_OOFTubularityMeasure
#define _Included_FijiITKInterface_OOFTubularityMeasure
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FijiITKInterface_OOFTubularityMeasure
 * Method:    OrientedFlux
 * Signature: ([B[FIIIIDDDDDILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_FijiITKInterface_OOFTubularityMeasure_OrientedFlux
  (JNIEnv *, jobject, jbyteArray, jfloatArray, jint, jint, jint, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
